import React,{useCallback,useEffect,useState} from 'react';
import {ScrollView,View,Text} from 'react-native';
import {colors,typography,spacing} from '../../../theme/theme';
import Card from '../../../components/Card';
import Button from '../../../components/Button';
import StatusBadge from '../../../components/StatusBadge';
import {getUser} from '../../../services/adminService';
import {Screen,Loading,ErrorBox,SectionTitle,Row,Divider,styles} from '../AdminUI';
export default function UserDetailScreen({route,navigation}){const {userId}=route.params;const [d,setD]=useState(null);const [loading,setLoading]=useState(true);const [error,setError]=useState(null);const load=useCallback(async()=>{try{setError(null);setD(await getUser(userId))}catch(e){setError(e.message)}finally{setLoading(false)}},[userId]);useEffect(()=>{load()},[load]);if(loading)return <Screen title="Utilisateur"><Loading/></Screen>;if(error)return <Screen title="Utilisateur"><ErrorBox message={error} onRetry={load}/></Screen>;const p=d.profile,w=d.wallet,t=d.transactions||[];return <Screen title="Détail utilisateur"><ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}><Card><Text style={typography.h2}>{p.username}</Text><Text style={[typography.body,styles.muted]}>{p.whatsapp_number}</Text><Text style={[typography.body,styles.muted]}>{p.country}</Text></Card><SectionTitle title="Wallet"/><Card><Row icon="wallet-outline" title={w?`${w.available_balance} U`:'Aucun wallet'} subtitle={w?`En attente: ${w.pending_balance} U`:''}/><Button title="Voir le wallet" onPress={()=>navigation.navigate('AdminUserWallet',{userId})}/></Card><SectionTitle title="Transactions"/><Card>{t.length?t.map((x,i)=><View key={x.id}><Row icon="swap-horizontal-outline" title={x.type} subtitle={new Date(x.created_at).toLocaleString('fr-FR')} right={<StatusBadge status={x.status}/>} onPress={()=>navigation.navigate('AdminTransactionDetail',{transactionId:x.id})}/>{i<t.length-1&&<Divider/>}</View>):<Row title="Aucune transaction" subtitle="Cet utilisateur n'a pas encore d'opération."/>}</Card></ScrollView></Screen>}
